### ISSUE TITLE
GBA advance an SP 101 grid LCD effect

### ISSUE THREAD

**Issue by ChipsLabs** [spiritualized1997/openFPGA-GBA#29]
Hi,
Is there a way to add GBA advance an SP 101 grid LCD effect like when we play cartridge ?

Thanks for the help

**Comment by MaddoScientisto** [comment]
looking at other similar questions, it seems like the analogue firmware still doesn't have that feature so cores can't use it yet

**Comment by ChipsLabs** [comment]
Ok sorry didn't see it on other post
Thanks for the answer
