### ISSUE TITLE
Volume is reduced compared to Official Pocket GBA core.  

### ISSUE THREAD

**Issue by SegaSnatcher** [spiritualized1997/openFPGA-GBA#7]
Here are video comparisons of the openFPGA GBA core at max volume vs the Official Pocket GBA core at max volume.

https://www.youtube.com/watch?v=Nb5l3qiFotQ

https://www.youtube.com/watch?v=2bl0f6a4mtA

**Comment by PriMieon** [comment]
I find it not too apparent in the videos but it is super noticeable in person! Huge decrease in volume

**Comment by rootjam** [comment]
i am having the same problem only GBA sound is low color and regular Gameboy are fine. I Put in my original cart and it blows the sound out of the water compared to the OpenFPGA

**Comment by SegaSnatcher** [comment]
> i am having the same problem only GBA sound is low color and regular Gameboy are fine. I Put in my original cart and it blows the sound out of the water compared to the OpenFPGA

The GB/GBC OpenFPGA volumes are lower as well vs using real carts or .Pocket files.

**Comment by PriMieon** [comment]
> > i am having the same problem only GBA sound is low color and regular Gameboy are fine. I Put in my original cart and it blows the sound out of the water compared to the OpenFPGA
> 
> The GB/GBC OpenFPGA volumes are lower as well vs using real carts or .Pocket files.

For sure. The volume is a lot quieter with the non-advance consoles

**Comment by SegaSnatcher** [comment]
1.1-beta-2 firmware that was rolled out today fixes the volume limit issues.
