### ISSUE TITLE
Incompatibility - Super Street Fighter 2 Turbo

### ISSUE THREAD

**Issue by mddifilippo89** [spiritualized1997/openFPGA-GBA#9]

**Comment by SegaSnatcher** [comment]
Game is working fine on my Pocket.

**Comment by mddifilippo89** [comment]
Its a copy that I've been using on my everdrive. I can try a new copy elsewhere and see if it works. Thanks.

**Comment by dietdietcokes** [comment]
It’s very likely your bios file is bad. The one I initially used resulted in an incorrect GBA startup sound and Mother 3 was having texture errors. After replacing the bios file, both issues were immediately fixed.

**Comment by mddifilippo89** [comment]
It was the rom. false alarm.
